###
# Knex database configuration to create database connections. The database, user,
# pass, and options variables should be set as described in the documentation
# of Sequelize as specified at:
#     http://knexjs.org/
###
knex:
  connection:
    password : "123456"